apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wl-example-metaphor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  project: default
  source:
    repoURL: git@github.com:kubefirst-ai/gitops.git
    path: registry/environments/wl-example/metaphor
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: wl-example
    namespace: wl-example
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true