apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: selfhosted-ai-vault-kv-secret
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  provider:
    vault:
      server: 'https://vault.kubefirst.ai'
      path: 'secret'
      version: 'v2'
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "selfhosted-ai-cluster-vault-bootstrap"
          key: "vault-token"
