apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: selfhosted-ai-cert-issuers
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '40'
spec:
  project: selfhosted-ai
  source:
    repoURL: git@github.com:kubefirst-ai/gitops.git
    path: registry/clusters/selfhosted-ai/cert-issuers
    targetRevision: HEAD
  destination:
    name: selfhosted-ai
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
