apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: wl-example-infrastructure
spec:
  providerConfigRef: 
    name: wl-example
  forProvider:
    source: Remote
    module: git::https://github.com/kubefirst-ai/gitops.git//terraform/civo/modules/workload-cluster?ref=main
    vars:
    - key: cluster_name
      value: wl-example
    - key: cluster_region
      value: lon1
    - key: environment
      value: wl-example
    - key: node_count
      value: "2"
    - key: node_type
      value: g4s.kube.large
    - key: is_gpu
      value: "false"
