apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://charts.loft.sh
    targetRevision: 0.15.5
    chart: vcluster-k8s
    helm:
      values: |
        syncer:
          extraArgs:
          - --tls-san=vcluster.kubefirst.ai
          - --kube-config-context-name=vcluster
          - --out-kube-config-server=https://vcluster.kubefirst.ai
          replicas: 4
        ingress:
          enabled: true
          pathType: ImplementationSpecific
          apiVersion: networking.k8s.io/v1
          ingressClassName: "nginx"
          host: vcluster.kubefirst.ai
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: HTTPS
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            
            
            
          tls:
            - secretName: vcluster-tls
              hosts:
                - vcluster.kubefirst.ai
  destination:
    name: in-cluster
    namespace: vcluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true