apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: vcluster
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  configuration: |
      terraform {
        backend "s3" {
          bucket   = "k1-state-store-spotlight-0vzcwy"
          key      = "registry/clusters/vcluster/infrastructure/provider-config/terraform.tfstate"
          endpoint = "https://objectstore.lon1.civo.com"

          region = "lon1"

          skip_credentials_validation = true
          skip_metadata_api_check     = true
          skip_region_validation      = true
          force_path_style            = true
        }
        required_providers {
          civo = {
            source = "civo/civo"
          }
          kubernetes = {
            source = "hashicorp/kubernetes"
            version = "2.23.0"
          }
          vault = {
            source = "hashicorp/vault"
            version = "3.19.0"
          }
        }
      }
      provider "civo" {
        region = ""
      }
  credentials:
  - filename: gen-nothing
    source: None
    secretRef:
      namespace: crossplane-system
      name: civo-creds
      key: token
  - filename: .git-credentials
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: git-credentials
      key: creds
