---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spotlight-argo-events-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '100'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:kubefirst-ai/gitops.git
    path: registry/clusters/spotlight/components/argo-events
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: argo-events
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
