apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: git@github.com:kubefirst-ai/gitops.git
    path: registry/clusters/spotlight/components/cert-manager
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
