apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '60'
spec:
  project: default
  source:
    repoURL: git@github.com:kubefirst-ai/gitops.git
    path: registry/clusters/spotlight/components/reloader
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
