apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: selfhosted-ai
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  configuration: |
      terraform {
        backend "s3" {
          bucket   = "k1-state-store-spotlight-0vzcwy"
          key      = "registry/clusters/selfhosted-ai/infrastructure/provider-config/terraform.tfstate"
          endpoint = "https://objectstore.lon1.civo.com"

          region = "lon1"

          skip_credentials_validation = true
          skip_metadata_api_check     = true
          skip_region_validation      = true
          force_path_style            = true
        }
        required_providers {
          civo = {
            source  = "civo/civo"
            version = "= 1.1.0"
          }
          helm = {
            source = "hashicorp/helm"
            version = "~> 2.15.0"
          }
        }
      }
      provider "civo" {
        credentials_file = "civo.json"
        region = "lon1"
      }
  credentials:
  - filename: civo.json
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: default-civo-creds
      key: config.json
  - filename: .git-credentials
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: git-credentials
      key: creds
