apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wl-example-cluster-secret-store
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '40'
spec:
  project: wl-example
  source:
    repoURL: git@github.com:kubefirst-ai/gitops.git
    path: registry/clusters/wl-example/cluster-secret-store
    targetRevision: HEAD
  destination:
    name: wl-example
    namespace: external-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
